# Step 5: merge everything, apply the hand-checked onset fixes, and write src/data.js.
import pathlib
ROOT = pathlib.Path(__file__).resolve().parents[2]  # repo root
WORK = ROOT / 'tools' / 'audio' / 'work'  # intermediate files (git-ignored)
WORK.mkdir(parents=True, exist_ok=True)
import json, re, base64
lines=json.load(open(WORK / "lines.json"))
audio=json.load(open(WORK / "audio.json"))
raw=[l.strip() for l in open(ROOT / "lyrics.txt") if l.strip()]
def norm(t): return re.sub(r"[^a-z0-9]","",t.lower())
# line start/end (manual fixes from whisper word review)
starts=[1.40,5.64,9.06,12.52,16.18,22.04,24.24,25.96,27.76,29.60,32.66,35.50,41.12,44.74,48.42,52.72,
        58.28,60.46,62.34,64.04,65.98,68.42,72.80,77.28,81.10,84.68,88.76,94.64,96.84,98.70,100.34,102.30,
        104.28,108.18,113.22,114.98,116.88,118.70,120.24,122.36,126.04,127.88,129.60,131.38,135.16]
ends=starts[1:]+[140.30]
override={
 4:{0:16.18}, 9:{3:30.58,4:30.90}, 10:{2:33.82}, 32:{0:104.28,1:106.86,2:107.30},
 33:{0:108.18,1:111.18}, 35:{0:114.98,1:115.94}, 37:{0:118.70,1:119.10,2:119.64},
 40:{2:126.52,3:127.0,4:127.44}, 41:{1:128.14,2:128.64,3:129.18}, 42:{2:130.60}, 43:{2:132.52},
 29:{0:98.70}, 25:{3:86.32}, 11:{0:38.40,1:38.76}, 26:{0:88.76,1:90.46,2:91.30,3:92.86,4:93.42,5:94.10},
 24:{0:81.10,1:81.86,2:82.00}, 44:{1:137.50,2:137.90,3:138.50,4:139.64},
}
out=[]
for i,text in enumerate(raw):
    toks=text.split()
    wt=lines[i]["words"]  # normalized tokens with times (may be None)
    # map display tokens -> times by walking normalized tokens
    times=[]; k=0
    for tok in toks:
        n=norm(tok)
        if not n: times.append(None); continue
        t=None
        if k<len(wt): t=wt[k][1]; k+=1
        times.append(t)
    for j,t in override.get(i,{}).items(): times[j]=t
    if i not in override or 0 not in override[i]:
        times[0]=starts[i] if times[0] is None or abs(times[0]-starts[i])>0.6 else min(times[0],starts[i])
    # interpolate missing
    for j in range(len(times)):
        if times[j] is None:
            prev=max([x for x in times[:j] if x is not None] or [starts[i]])
            nxt=[x for x in times[j+1:] if x is not None]
            nx=nxt[0] if nxt else min(ends[i], prev+0.6)
            times[j]=round(prev+(nx-prev)*0.5,2)
    # enforce monotonic
    for j in range(1,len(times)):
        if times[j]<times[j-1]: times[j]=times[j-1]+0.05
    rec={"t0":starts[i],"t1":ends[i],"w":[[tok,round(t,2)] for tok,t in zip(toks,times)]}
    if i==33: rec["stutter"]=[110.00,110.84,111.18]
    out.append(rec)
    print(i, starts[i], ends[i], " ".join(f"{tok}@{t:.2f}" for tok,t in zip(toks,times)))
def b64(arr): return base64.b64encode(bytes(int(max(0,min(1,v))*255) for v in arr)).decode()
js = "// Generated by gendata.py from Whisper word timings + librosa analysis of pdoom.mp3\n"
js += "const SONG = " + json.dumps({"duration":156.65,"bpm":round(audio["tempo"],3),"lines":out}, separators=(",",":")) + ";\n"
js += "const BEATS = " + json.dumps(audio["beats"], separators=(",",":")) + ";\n"
js += "const ENV_FPS = 30;\nconst ENV_RMS_B64 = '" + b64(audio["rms"]) + "';\nconst ENV_LOW_B64 = '" + b64(audio["low"]) + "';\nconst ENV_HIGH_B64 = '" + b64(audio["high"]) + "';\n"
open(ROOT / "src" / "data.js","w").write(js)
print(len(js))
